### ISSUE TITLE
Implement XDP logger

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/XRT#1]
## Why?

Debugging XDP is hard because there is no logging mechanism other than print statements.

## Solution

Implement logger like the driver code.

## Structure

```
- xdp
   - profile
   - debug
   - appdebug
   - util
      - logger.h
      - logger.cpp
```

## TODO

- [x] create `logger.h` and `logger.cpp`
- [x] create a dummy logging function
- [x] modify the XDP cmake to compile the dummy logging function
- [x] add the stream object
- [x] in the core constructor, check xrt.ini parameter and open stream if necessary
- [x] in the logging function, check if stream is opened and log if opened

**Comment by tianhaoz95** [comment]
done and submitted the PR
